Instance: questionnaire-cvd-risk-assessment
InstanceOf: Questionnaire
Usage: #example
Title: "Questionnaire: CVD risk assessment (ESPBI form 1)"
Description: "Illustrative FHIR Questionnaire for the national **patient cardiovascular disease risk assessment** electronic form (PDF tables 10.5–10.9). Extend with full field parity in production."
* url = "https://hl7.lt/fhir/cvd/Questionnaire/cvd-risk-assessment"
* version = "0.1.0"
* name = "CvdRiskAssessment"
* title = "Patient cardiovascular disease risk assessment questionnaire"
* status = #draft
* subjectType = #Patient
* date = "2025-10-01"
* publisher = "HL7 Lithuania"
* description = "Representative subset of programme fields: context, chronic diseases, key risk factors, anthropometrics, blood pressure, lipid panel, SCORE2, risk group, plus optional items aligned with input/fsh/migration/mapping.md (extended parity)."

* item[0].linkId = "grp-context"
* item[0].text = "Context (registrar, institution, workstation — not itemised in this illustrative Questionnaire)."
* item[0].type = #group
* item[0].item[0].linkId = "evaluation-datetime"
* item[0].item[0].text = "Evaluation date and time"
* item[0].item[0].type = #dateTime
* item[0].item[0].definition = $cvd-risk-assessment-lt-cvd-url
* item[0].item[0].required = true

* item[1].linkId = "grp-chronic"
* item[1].text = "Accompanying chronic diseases (programme list)"
* item[1].type = #group
* item[1].item[0].linkId = "chronic-condition-summary"
* item[1].item[0].text = "Relevant chronic conditions"
* item[1].item[0].type = #text
* item[1].item[0].definition = $cvd-chronic-condition-lt-cvd-url

* item[2].linkId = "grp-risk-factors"
* item[2].text = "Risk factors"
* item[2].type = #group
* item[2].item[0].linkId = "risk-factor-hypertension"
* item[2].item[0].text = "Arterial hypertension"
* item[2].item[0].type = #coding
* item[2].item[0].definition = $risk-factor-status-lt-cvd-url
* item[2].item[0].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[2].item[0].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-untreated "There is, untreated"
* item[2].item[0].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#risk-factor-treated "There is, treated"
* item[2].item[0].required = true
* item[2].item[1].linkId = "risk-factor-dyslipidemia"
* item[2].item[1].text = "Dyslipidemia"
* item[2].item[1].type = #coding
* item[2].item[1].definition = $risk-factor-status-lt-cvd-url
* item[2].item[1].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[2].item[1].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-untreated "There is, untreated"
* item[2].item[1].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#risk-factor-treated "There is, treated"
* item[2].item[1].required = true
* item[2].item[2].linkId = "risk-factor-diabetes"
* item[2].item[2].text = "Diabetes"
* item[2].item[2].type = #coding
* item[2].item[2].definition = $risk-factor-status-lt-cvd-url
* item[2].item[2].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[2].item[2].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-untreated "There is, untreated"
* item[2].item[2].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#risk-factor-treated "There is, treated"
* item[2].item[2].required = true
* item[2].item[3].linkId = "risk-factor-glucose-tolerance"
* item[2].item[3].text = "Glucose tolerance disorder or fasting glucose disorder"
* item[2].item[3].type = #coding
* item[2].item[3].definition = $risk-factor-status-lt-cvd-url
* item[2].item[3].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[2].item[3].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-untreated "There is, untreated"
* item[2].item[3].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#risk-factor-treated "There is, treated"
* item[2].item[3].required = true
* item[2].item[4].linkId = "risk-factor-familial-hypercholesterolemia"
* item[2].item[4].text = "Familial hypercholesterolemia"
* item[2].item[4].type = #coding
* item[2].item[4].definition = $risk-factor-status-lt-cvd-url
* item[2].item[4].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[2].item[4].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-present "There is"
* item[2].item[4].required = true
* item[2].item[5].linkId = "risk-factor-smoking"
* item[2].item[5].text = "Smoking"
* item[2].item[5].type = #coding
* item[2].item[5].definition = $sd-lifestyle-tobacco-use
* item[2].item[5].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#smoking-never "Did not smoke"
* item[2].item[5].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#smoking-current "Smokes"
* item[2].item[5].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#smoking-former "Smoked before"
* item[2].item[5].required = true
* item[2].item[5].item[0].linkId = "smoking-duration-years"
* item[2].item[5].item[0].text = "Smoking duration (years)"
* item[2].item[5].item[0].type = #decimal
* item[2].item[5].item[0].definition = $sd-lifestyle-tobacco-use-duration
* item[2].item[5].item[0].enableWhen.question = "risk-factor-smoking"
* item[2].item[5].item[0].enableWhen.operator = #=
* item[2].item[5].item[0].enableWhen.answerCoding = $cvd-questionnaire-options-cs#smoking-current
* item[2].item[5].item[1].linkId = "smoking-type"
* item[2].item[5].item[1].text = "Form of smoking"
* item[2].item[5].item[1].type = #coding
* item[2].item[5].item[1].definition = $sd-lifestyle-tobacco-type-used
* item[2].item[5].item[1].repeats = true
* item[2].item[5].item[1].enableWhen.question = "risk-factor-smoking"
* item[2].item[5].item[1].enableWhen.operator = #=
* item[2].item[5].item[1].enableWhen.answerCoding = $cvd-questionnaire-options-cs#smoking-current
* item[2].item[6].linkId = "risk-factor-physical-activity"
* item[2].item[6].text = "Physical activity"
* item[2].item[6].type = #coding
* item[2].item[6].definition = $sd-lifestyle-physical-activity
* item[2].item[6].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#pa-sufficient "Sufficient"
* item[2].item[6].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#pa-insufficient "Insufficient"
* item[2].item[6].required = true
* item[2].item[7].linkId = "risk-factor-nutrition"
* item[2].item[7].text = "Nutrition"
* item[2].item[7].type = #coding
* item[2].item[7].definition = $sd-lifestyle-nutrition
* item[2].item[7].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#nutrition-balanced "Balanced"
* item[2].item[7].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#nutrition-unbalanced "Unbalanced"
* item[2].item[7].required = true
* item[2].item[8].linkId = "risk-factor-alcohol"
* item[2].item[8].text = "Alcohol consumption"
* item[2].item[8].type = #coding
* item[2].item[8].definition = $sd-lifestyle-alcohol
* item[2].item[8].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#alcohol-no "No"
* item[2].item[8].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#alcohol-yes "Yes"
* item[2].item[8].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#alcohol-unknown "Unknown"
* item[2].item[8].required = true
* item[2].item[8].item[0].linkId = "audit-c-score"
* item[2].item[8].item[0].text = "AUDIT / AUDIT-C test result interpretation"
* item[2].item[8].item[0].type = #decimal
* item[2].item[8].item[0].definition = $sd-lifestyle-audit-c
* item[2].item[8].item[0].enableWhen.question = "risk-factor-alcohol"
* item[2].item[8].item[0].enableWhen.operator = #=
* item[2].item[8].item[0].enableWhen.answerCoding = $cvd-questionnaire-options-cs#alcohol-yes
* item[2].item[9].linkId = "risk-factor-family-cvd"
* item[2].item[9].text = "Family history of early CVD (men <55, women <60) or early cardiac death"
* item[2].item[9].type = #coding
* item[2].item[9].definition = $sd-lifestyle-family-history-cvd
* item[2].item[9].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#family-no "No"
* item[2].item[9].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#family-yes "Yes"
* item[2].item[9].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#family-unknown "Unknown"
* item[2].item[9].required = true
* item[2].item[10].linkId = "risk-factor-family-diabetes"
* item[2].item[10].text = "Family history of diabetes"
* item[2].item[10].type = #coding
* item[2].item[10].definition = $sd-lifestyle-family-history-diabetes
* item[2].item[10].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#family-no "No"
* item[2].item[10].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#family-yes "Yes"
* item[2].item[10].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#family-unknown "Unknown"
* item[2].item[10].required = true

* item[3].linkId = "grp-objective"
* item[3].text = "Objective condition and investigations"
* item[3].type = #group
* item[3].item[0].linkId = "height-cm"
* item[3].item[0].text = "Height (cm)"
* item[3].item[0].type = #decimal
* item[3].item[0].definition = $sd-vitalsigns-body-height
* item[3].item[0].required = true
* item[3].item[1].linkId = "weight-kg"
* item[3].item[1].text = "Weight (kg)"
* item[3].item[1].type = #decimal
* item[3].item[1].definition = $sd-vitalsigns-body-weight
* item[3].item[1].required = true
* item[3].item[2].linkId = "waist-cm"
* item[3].item[2].text = "Waist circumference (cm)"
* item[3].item[2].type = #decimal
* item[3].item[2].definition = $sd-vitalsigns-waist
* item[3].item[2].required = true
* item[3].item[3].linkId = "bp-systolic"
* item[3].item[3].text = "Systolic blood pressure (mmHg)"
* item[3].item[3].type = #decimal
* item[3].item[3].definition = $sd-vitalsigns-bp-panel
* item[3].item[3].required = true
* item[3].item[4].linkId = "bp-diastolic"
* item[3].item[4].text = "Diastolic blood pressure (mmHg)"
* item[3].item[4].type = #decimal
* item[3].item[4].definition = $sd-vitalsigns-bp-panel
* item[3].item[4].required = true
* item[3].item[5].linkId = "heart-rate"
* item[3].item[5].text = "Heart rate (bpm)"
* item[3].item[5].type = #decimal
* item[3].item[5].definition = $sd-vitalsigns-heart-rate
* item[3].item[5].required = true
* item[3].item[6].linkId = "bmi-calculated"
* item[3].item[6].text = "BMI (kg/m², automatically calculated)"
* item[3].item[6].type = #decimal
* item[3].item[6].definition = $sd-vitalsigns-bmi
* item[3].item[6].required = true
* item[3].item[7].linkId = "abdominal-obesity"
* item[3].item[7].text = "Abdominal obesity (waist circumference men ≥ 102 cm, women ≥ 88 cm)"
* item[3].item[7].type = #coding
* item[3].item[7].definition = $sd-vitalsigns-waist
* item[3].item[7].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[3].item[7].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-present "There is"
* item[3].item[7].required = true
* item[3].item[7].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/rendering-xhtml"
* item[3].item[7].text.extension[0].valueString = "Derived from WaistCircumference observation interpretation. Use interpretation code to indicate obesity status."
* item[3].item[8].linkId = "obesity-bmi"
* item[3].item[8].text = "Obesity (BMI ≥ 25)"
* item[3].item[8].type = #coding
* item[3].item[8].definition = $sd-vitalsigns-bmi
* item[3].item[8].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[3].item[8].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-present "There is"
* item[3].item[8].required = true

* item[4].linkId = "grp-lipidogram"
* item[4].text = "Lipidogram"
* item[4].type = #group
* item[4].item[0].linkId = "lipid-tc"
* item[4].item[0].text = "Total cholesterol (mmol/l)"
* item[4].item[0].type = #decimal
* item[4].item[0].definition = $sd-lab-total-cholesterol
* item[4].item[0].required = true
* item[4].item[1].linkId = "lipid-hdl"
* item[4].item[1].text = "HDL cholesterol (mmol/l)"
* item[4].item[1].type = #decimal
* item[4].item[1].definition = $sd-lab-hdl
* item[4].item[1].required = true
* item[4].item[2].linkId = "lipid-non-hdl"
* item[4].item[2].text = "Non-HDL cholesterol (mmol/l)"
* item[4].item[2].type = #decimal
* item[4].item[2].definition = $sd-lab-non-hdl
* item[4].item[2].required = true
* item[4].item[3].linkId = "lipid-ldl"
* item[4].item[3].text = "LDL cholesterol (mmol/l)"
* item[4].item[3].type = #decimal
* item[4].item[3].definition = $sd-lab-ldl
* item[4].item[3].required = true
* item[4].item[4].linkId = "lipid-tg"
* item[4].item[4].text = "Triglycerides (mmol/l)"
* item[4].item[4].type = #decimal
* item[4].item[4].definition = $sd-lab-triglycerides
* item[4].item[4].required = true

* item[5].linkId = "grp-risk-estimate"
* item[5].text = "Risk estimate and group"
* item[5].type = #group
* item[5].item[0].linkId = "score2-percent"
* item[5].item[0].text = "SCORE2 cardiovascular risk (%)"
* item[5].item[0].type = #decimal
* item[5].item[0].definition = $cvd-risk-assessment-lt-cvd-url
* item[5].item[1].linkId = "metabolic-syndrome"
* item[5].item[1].text = "Metabolic syndrome (at least 3 out of 5 NCEP ATP III criteria)"
* item[5].item[1].type = #coding
* item[5].item[1].definition = $sd-lifestyle-metabolic-syndrome
* item[5].item[1].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[5].item[1].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#risk-factor-present "Yes"
* item[5].item[1].required = true
* item[5].item[2].linkId = "risk-group-cvd"
* item[5].item[2].text = "Risk group for heart and vascular diseases"
* item[5].item[2].type = #coding
* item[5].item[2].definition = $risk-group-observation-lt-cvd-url
* item[5].item[2].answerOption[0].valueCoding = $cvd-questionnaire-options-cs#cvd-rg-small-medium "Small to medium"
* item[5].item[2].answerOption[1].valueCoding = $cvd-questionnaire-options-cs#cvd-rg-large "Large"
* item[5].item[2].answerOption[2].valueCoding = $cvd-questionnaire-options-cs#cvd-rg-very-large "Very large"
* item[5].item[2].required = true
* item[5].item[3].linkId = "albumin-creatinine-ratio"
* item[5].item[3].text = "Albumin/Creatinine ratio (for patients with diabetes)"
* item[5].item[3].type = #decimal
* item[5].item[3].definition = $sd-lab-acr

* item[6].linkId = "grp-migration-md-parity"
* item[6].text = "Extended parity (migration/mapping.md — missing-concepts rows)"
* item[6].type = #group
* item[6].item[0].linkId = "mig-encounter"
* item[6].item[0].text = "Encounter (visit id / context)"
* item[6].item[0].type = #string
* item[6].item[0].definition = $sd-base-encounter-lt
* item[6].item[1].linkId = "mig-practitioner-role"
* item[6].item[1].text = "PractitionerRole (workplace / specialist)"
* item[6].item[1].type = #string
* item[6].item[1].definition = $sd-base-practitioner-role-lt
* item[6].item[2].linkId = "mig-heart-rate"
* item[6].item[2].text = "Heart rate (bpm)"
* item[6].item[2].type = #decimal
* item[6].item[2].definition = $sd-vitalsigns-heart-rate
* item[6].item[3].linkId = "mig-bmi"
* item[6].item[3].text = "BMI (kg/m²)"
* item[6].item[3].type = #decimal
* item[6].item[3].definition = $sd-vitalsigns-bmi
* item[6].item[4].linkId = "mig-glucose-fasting"
* item[6].item[4].text = "Fasting glucose (mmol/l)"
* item[6].item[4].type = #decimal
* item[6].item[4].definition = $sd-lab-glucose-venous
* item[6].item[4].required = true
* item[6].item[5].linkId = "mig-hba1c"
* item[6].item[5].text = "HbA1c (%)"
* item[6].item[5].type = #decimal
* item[6].item[5].definition = $sd-lab-hba1c
* item[6].item[5].required = true
* item[6].item[6].linkId = "mig-creatinine"
* item[6].item[6].text = "Creatinine"
* item[6].item[6].type = #decimal
* item[6].item[6].definition = $sd-lab-creatinine
* item[6].item[6].required = true
* item[6].item[7].linkId = "mig-egfr"
* item[6].item[7].text = "eGFR"
* item[6].item[7].type = #decimal
* item[6].item[7].definition = $sd-lab-egfr
* item[6].item[7].required = true
* item[6].item[8].linkId = "mig-alcohol"
* item[6].item[8].text = "Alcohol consumption (summary)"
* item[6].item[8].type = #string
* item[6].item[8].definition = $sd-lifestyle-alcohol
* item[6].item[9].linkId = "mig-physical-activity"
* item[6].item[9].text = "Physical activity (summary)"
* item[6].item[9].type = #string
* item[6].item[9].definition = $sd-lifestyle-physical-activity
* item[6].item[10].linkId = "mig-nutrition"
* item[6].item[10].text = "Dietary habits / nutrition"
* item[6].item[10].type = #string
* item[6].item[10].definition = $sd-lifestyle-nutrition
* item[6].item[11].linkId = "mig-family-cvd"
* item[6].item[11].text = "Family history of CVD"
* item[6].item[11].type = #string
* item[6].item[11].definition = $sd-lifestyle-family-history-cvd
* item[6].item[12].linkId = "mig-referral"
* item[6].item[12].text = "Referral (cardiology / service)"
* item[6].item[12].type = #string
* item[6].item[12].definition = $sd-base-service-request-lt
* item[6].item[13].linkId = "mig-follow-up-appointment"
* item[6].item[13].text = "Follow-up visit (appointment)"
* item[6].item[13].type = #dateTime
* item[6].item[13].definition = $sd-base-appointment-lt
* item[6].item[14].linkId = "mig-achievement-round"
* item[6].item[14].text = "Achievement evaluation (narrative)"
* item[6].item[14].type = #text
* item[6].item[14].definition = $sd-base-observation-lt
* item[6].item[15].linkId = "mig-chronic-additional"
* item[6].item[15].text = "Additional chronic conditions"
* item[6].item[15].type = #text
* item[6].item[15].definition = $cvd-chronic-condition-lt-cvd-url

* item[7].linkId = "grp-ig-example-parity"
* item[7].text = "IG example parity (migration already-covered)"
* item[7].type = #group
* item[7].item[0].linkId = "ac-patient-context"
* item[7].item[0].text = "Patient (context note)"
* item[7].item[0].type = #string
* item[7].item[1].linkId = "ac-practitioner-context"
* item[7].item[1].text = "Practitioner (context note)"
* item[7].item[1].type = #string
* item[7].item[2].linkId = "ac-organization-context"
* item[7].item[2].text = "Organization (context note)"
* item[7].item[2].type = #string
* item[7].item[3].linkId = "ac-ekg-summary"
* item[7].item[3].text = "ECG (summary)"
* item[7].item[3].type = #text
* item[7].item[3].definition = $ekg-lt-cvd-url
* item[7].item[4].linkId = "ac-medication-context"
* item[7].item[4].text = "Medications (context)"
* item[7].item[4].type = #text
* item[7].item[4].definition = $medication-statement-lt-cvd-url
* item[7].item[5].linkId = "ac-diabetes-duration"
* item[7].item[5].text = "Diabetes duration"
* item[7].item[5].type = #text
* item[7].item[5].definition = $diabetes-duration-status-lt-cvd-url

Instance: questionnaireresponse-cvd-risk-assessment-example
InstanceOf: QuestionnaireResponse
Usage: #example
Title: "QuestionnaireResponse: CVD risk assessment (example)"
Description: "Example answers for the CVD risk assessment Questionnaire, aligned with other CVD IG examples (SCORE2 24%, high risk group)."
* questionnaire = "https://hl7.lt/fhir/cvd/Questionnaire/cvd-risk-assessment"
* status = #completed
* subject = Reference(Patient/patient-male-example)
* authored = "2025-10-01T09:00:00Z"
* author = Reference(Practitioner/practitioner-example)

* item[0].linkId = "grp-context"
* item[0].item[0].linkId = "evaluation-datetime"
* item[0].item[0].answer.valueDateTime = "2025-10-01T09:00:00Z"

* item[1].linkId = "grp-chronic"
* item[1].item[0].linkId = "chronic-condition-summary"
* item[1].item[0].answer.valueString = "Heart failure (I50) — example only"

* item[2].linkId = "grp-risk-factors"
* item[2].item[0].linkId = "risk-factor-hypertension"
* item[2].item[0].answer.valueCoding = $cvd-questionnaire-options-cs#risk-factor-treated "There is, treated"
* item[2].item[1].linkId = "risk-factor-dyslipidemia"
* item[2].item[1].answer.valueCoding = $cvd-questionnaire-options-cs#risk-factor-treated "There is, treated"
* item[2].item[2].linkId = "risk-factor-diabetes"
* item[2].item[2].answer.valueCoding = $cvd-questionnaire-options-cs#risk-factor-no "No"
* item[2].item[3].linkId = "risk-factor-smoking"
* item[2].item[3].answer.valueCoding = $cvd-questionnaire-options-cs#smoking-never "Did not smoke"

* item[3].linkId = "grp-objective"
* item[3].item[0].linkId = "height-cm"
* item[3].item[0].answer.valueDecimal = 178
* item[3].item[1].linkId = "weight-kg"
* item[3].item[1].answer.valueDecimal = 88
* item[3].item[2].linkId = "waist-cm"
* item[3].item[2].answer.valueDecimal = 98
* item[3].item[3].linkId = "bp-systolic"
* item[3].item[3].answer.valueDecimal = 132
* item[3].item[4].linkId = "bp-diastolic"
* item[3].item[4].answer.valueDecimal = 84

* item[4].linkId = "grp-lipidogram"
* item[4].item[0].linkId = "lipid-tc"
* item[4].item[0].answer.valueDecimal = 5.8
* item[4].item[1].linkId = "lipid-hdl"
* item[4].item[1].answer.valueDecimal = 1.1
* item[4].item[2].linkId = "lipid-ldl"
* item[4].item[2].answer.valueDecimal = 3.6
* item[4].item[3].linkId = "lipid-tg"
* item[4].item[3].answer.valueDecimal = 1.9

* item[5].linkId = "grp-risk-estimate"
* item[5].item[0].linkId = "score2-percent"
* item[5].item[0].answer.valueDecimal = 24
* item[5].item[1].linkId = "risk-group-cvd"
* item[5].item[1].answer.valueCoding = $cvd-questionnaire-options-cs#cvd-rg-large "Large"

* item[6].linkId = "grp-migration-md-parity"
* item[6].item[0].linkId = "mig-encounter"
* item[6].item[0].answer.valueString = "Outpatient CVD assessment — example"
* item[6].item[1].linkId = "mig-practitioner-role"
* item[6].item[1].answer.valueString = "Cardiologist — example"
* item[6].item[2].linkId = "mig-heart-rate"
* item[6].item[2].answer.valueDecimal = 72
* item[6].item[3].linkId = "mig-bmi"
* item[6].item[3].answer.valueDecimal = 27.8
* item[6].item[4].linkId = "mig-glucose-fasting"
* item[6].item[4].answer.valueDecimal = 5.2
* item[6].item[5].linkId = "mig-hba1c"
* item[6].item[5].answer.valueDecimal = 5.4
* item[6].item[6].linkId = "mig-creatinine"
* item[6].item[6].answer.valueDecimal = 88
* item[6].item[7].linkId = "mig-egfr"
* item[6].item[7].answer.valueDecimal = 82
* item[6].item[8].linkId = "mig-alcohol"
* item[6].item[8].answer.valueString = "Occasional — example"
* item[6].item[9].linkId = "mig-physical-activity"
* item[6].item[9].answer.valueString = "Walks 30 min/d — example"
* item[6].item[10].linkId = "mig-nutrition"
* item[6].item[10].answer.valueString = "Mediterranean-style — example"
* item[6].item[11].linkId = "mig-family-cvd"
* item[6].item[11].answer.valueString = "Father MI at 60 — example"
* item[6].item[12].linkId = "mig-referral"
* item[6].item[12].answer.valueString = "None — example"
* item[6].item[13].linkId = "mig-follow-up-appointment"
* item[6].item[13].answer.valueDateTime = "2026-03-01T09:00:00Z"
* item[6].item[14].linkId = "mig-achievement-round"
* item[6].item[14].answer.valueString = "Use prevention-plan Questionnaire for formal achievement block."
* item[6].item[15].linkId = "mig-chronic-additional"
* item[6].item[15].answer.valueString = "None additional — example"

* item[7].linkId = "grp-ig-example-parity"
* item[7].item[0].linkId = "ac-patient-context"
* item[7].item[0].answer.valueString = "patient-male-example"
* item[7].item[1].linkId = "ac-practitioner-context"
* item[7].item[1].answer.valueString = "practitioner-example"
* item[7].item[2].linkId = "ac-organization-context"
* item[7].item[2].answer.valueString = "organization-example"
* item[7].item[3].linkId = "ac-ekg-summary"
* item[7].item[3].answer.valueString = "Normal — example (see observation-ekg-normal-example)"
* item[7].item[4].linkId = "ac-medication-context"
* item[7].item[4].answer.valueString = "Statin — example (see medication-statement-screening-example)"
* item[7].item[5].linkId = "ac-diabetes-duration"
* item[7].item[5].answer.valueString = "Not applicable — example"
