// Questionnaire linkId CodeSystems and mapping target registry for ConceptMaps (cross-IG narrative).

CodeSystem: CvdQuestionnaireRiskAssessmentItem
Id: cvd-questionnaire-risk-assessment-item
Title: "CVD risk assessment questionnaire item (linkId)"
Description: "Stable linkId values for the illustrative ESPBI form 1 Questionnaire; used as ConceptMap source codes."
* ^url = $cvd-questionnaire-risk-assessment-item-cs-url
* ^version = "0.1.0"
* ^status = #draft
* ^experimental = true
* ^caseSensitive = true
* ^content = #complete
* ^publisher = "HL7 Lithuania"
* #grp-context "Context group"
* #evaluation-datetime "Evaluation date and time"
* #grp-chronic "Accompanying chronic diseases"
* #chronic-condition-summary "Chronic conditions summary"
* #grp-risk-factors "Risk factors"
* #risk-factor-hypertension "Arterial hypertension"
* #risk-factor-dyslipidemia "Dyslipidemia"
* #risk-factor-diabetes "Diabetes"
* #risk-factor-smoking "Smoking"
* #grp-objective "Objective condition and investigations"
* #height-cm "Height (cm)"
* #weight-kg "Weight (kg)"
* #waist-cm "Waist circumference (cm)"
* #bp-systolic "Systolic blood pressure (mmHg)"
* #bp-diastolic "Diastolic blood pressure (mmHg)"
* #grp-lipidogram "Lipidogram"
* #lipid-tc "Total cholesterol (mmol/l)"
* #lipid-hdl "HDL cholesterol (mmol/l)"
* #lipid-ldl "LDL cholesterol (mmol/l)"
* #lipid-tg "Triglycerides (mmol/l)"
* #grp-risk-estimate "Risk estimate and group"
* #score2-percent "SCORE2 cardiovascular risk (%)"
* #risk-group-cvd "Risk group for heart and vascular diseases"
* #grp-migration-md-parity "Migration mapping.md — extended parity"
* #mig-encounter "Encounter (visit context)"
* #mig-practitioner-role "PractitionerRole (workplace)"
* #mig-heart-rate "Heart rate (bpm)"
* #mig-bmi "BMI (kg/m²)"
* #mig-glucose-fasting "Fasting glucose (mmol/l)"
* #mig-hba1c "HbA1c (%)"
* #mig-creatinine "Creatinine"
* #mig-egfr "eGFR"
* #mig-alcohol "Alcohol consumption"
* #mig-physical-activity "Physical activity (summary)"
* #mig-nutrition "Dietary habits / nutrition"
* #mig-family-cvd "Family history of CVD"
* #mig-referral "Referral"
* #mig-follow-up-appointment "Follow-up visit / appointment"
* #mig-achievement-round "Achievement evaluation (narrative)"
* #mig-chronic-additional "Additional chronic conditions"
* #grp-ig-example-parity "IG example parity (migration already-covered)"
* #ac-patient-context "Patient (context note)"
* #ac-practitioner-context "Practitioner (context note)"
* #ac-organization-context "Organization (context note)"
* #ac-ekg-summary "ECG (summary)"
* #ac-medication-context "Medications (context)"
* #ac-diabetes-duration "Diabetes duration"

CodeSystem: CvdQuestionnairePreventionPlanItem
Id: cvd-questionnaire-prevention-plan-item
Title: "CVD prevention plan questionnaire item (linkId)"
Description: "Stable linkId values for the illustrative ESPBI form 2 Questionnaire; used as ConceptMap source codes."
* ^url = $cvd-questionnaire-prevention-plan-item-cs-url
* ^version = "0.1.0"
* ^status = #draft
* ^experimental = true
* ^caseSensitive = true
* ^content = #complete
* ^publisher = "HL7 Lithuania"
* #grp-plan-header "Plan header"
* #plan-created-datetime "Plan creation date and time"
* #plan-risk-group "Risk group (plan)"
* #plan-target-ldl "Target LDL cholesterol"
* #plan-smoking-cessation "Quitting smoking (interventions)"
* #grp-plan-lifestyle "Lifestyle and weight"
* #plan-physical-activity "Physical activity plan"
* #plan-target-bmi "Target BMI (kg/m²)"
* #grp-achievement "Achievement evaluation"
* #achievement-datetime "Achievement evaluation date and time"
* #achievement-ldl-mmol "Achieved LDL cholesterol (mmol/l)"
* #achievement-ldl-target-met "Target LDL achieved (boolean)"
* #achievement-bp-systolic "Current systolic BP (mmHg)"
* #achievement-bp-diastolic "Current diastolic BP (mmHg)"
* #achievement-bp-target-met "Target BP achieved (boolean)"
* #achievement-comments "Achievement evaluator comments"
* #achievement-smoking-quit "Smoking cessation achieved"

CodeSystem: CvdQuestionnaireMappingTarget
Id: cvd-questionnaire-mapping-target
Title: "CVD questionnaire mapping target (profiles)"
Description: "Target codes for ConceptMap rows: Lithuanian programme StructureDefinitions and related profiles referenced from ESPBI Questionnaires."
* ^url = $cvd-questionnaire-mapping-target-cs-url
* ^version = "0.1.0"
* ^status = #draft
* ^experimental = true
* ^caseSensitive = true
* ^content = #complete
* ^publisher = "HL7 Lithuania"
* #cvd-risk-assessment-lt-cvd "CVDRiskAssessmentLtCvd"
* #cvd-chronic-condition-lt-cvd "CvdChronicConditionLtCvd"
* #risk-factor-status-lt-cvd "RiskFactorStatusLtCvd"
* #tobacco-use-lt-lifestyle "TobaccoUseLtLifestyle"
* #body-height "BodyHeight (Vital Signs)"
* #body-weight "BodyWeight (Vital Signs)"
* #waist-circumference "WaistCircumference (Vital Signs)"
* #blood-pressure-panel "BloodPressurePanel (Vital Signs)"
* #total-cholesterol-lab-lt "TotalCholesterolLabLt"
* #cholesterol-hdl-lab-lt "CholesterolHdlLabLt"
* #cholesterol-ldl-lab-lt "CholesterolLdlLabLt"
* #triglycerides-lab-lt "TriglyceridesLabLt"
* #lipidogram-lab-lt "LipidogramLabLt"
* #risk-group-observation-lt-cvd "RiskGroupObservationLtCvd"
* #care-plan-lt-cvd "CarePlanLtCvd"
* #risk-group-ext-lt-cvd "RiskGroupExtLtCvd"
* #physical-activity-lt-lifestyle "PhysicalActivityLtLifestyle"
* #bmi "BMI (Vital Signs)"
* #observation-lt "ObservationLt (LT Base)"
* #encounter-lt "EncounterLt (LT Base)"
* #practitioner-role-lt "PractitionerRoleLt (LT Base)"
* #service-request-lt "ServiceRequestLt (LT Base)"
* #appointment-lt "AppointmentLt (LT Base)"
* #patient-lt "PatientLt (LT Base)"
* #practitioner-lt "PractitionerLt (LT Base)"
* #organization-lt "OrganizationLt (LT Base)"
* #heart-rate "HeartRate (Vital Signs)"
* #glucose-venous-lab-lt "GlucoseVenousLabLt"
* #hba1c-lab-lt "Hba1cLabLt"
* #creatinine-test-lab-lt "CreatinineTestLabLt"
* #egfr-lab-lt "EgfrLabLt"
* #alcohol-consumption-lt-lifestyle "AlcoholConsumptionLtLifestyle"
* #nutrition-lt-lifestyle "NutritionLtLifestyle"
* #family-history-cvd-lt-lifestyle "FamilyHistoryCvdLtLifestyle"
* #ekg-lt-cvd "EKGLtCvd"
* #medication-statement-lt-cvd "MedicationStatementLtCvd"
* #diabetes-duration-status-lt-cvd "DiabetesDurationStatusLtCvd"
